name: Lint Check (pre-commit)

on:
  pull_request_target:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: pre-commit
    permissions:
      contents: read
      checks: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

        # See:
        # https://github.com/tj-actions/changed-files?tab=readme-ov-file#using-local-git-directory-
      - uses: pre-commit/action@v3.0.1
        continue-on-error: true

      - name: suggester / pre-commit
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: pre-commit
          level: warning
          reviewdog_flags: "-fail-level=error"
